trigger: none

pool:
  name: Local_Windows_PC  # Replace with your local agent pool

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '"C:\Users\z0038b6b\source\repos\TestPipeline\TestPipeline_LWin_RLinux.ps1"'

